"""added password field

Revision ID: 540cf5f7dbe8
Revises: d9d9dffd7c3a
Create Date: 2023-11-18 23:56:13.872509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '540cf5f7dbe8'
down_revision = 'd9d9dffd7c3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
